version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
      - node_modules:/src/node_modules
    working_dir: "/src"
    ports:
      - "3100:3100"
    tty: true
    environment:
      - HOST=0.0.0.0
      - PORT=3100
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    command: npm run dev

networks: 
    app-network:

volumes:
  node_modules: